Adam feedback
Azure/AKS-Landing-Zone-Accelerator pull request #25
Opened 2022-07-08 15:47 UTC by MattLeach25

2022-07-13 00:38 UTC, mosabami requested changes

2022-07-13 00:38 UTC, mosabami commented on Scenarios/AKS-Secure-Baseline-PrivateCluster/Bicep/04-Network-LZ/parameters-main.json
> +      "value": "ESLZ-SPOKE-Matt"
remove matt

2022-07-13 00:38 UTC, mosabami commented on Scenarios/AKS-Secure-Baseline-PrivateCluster/Bicep/04-Network-LZ/parameters-main.json
> +      "value": "ESLZ-HUB-Matt"
remove matt

2022-07-18 13:22 UTC, MattLeach25 commented on Scenarios/AKS-Secure-Baseline-PrivateCluster/Bicep/04-Network-LZ/parameters-main.json
> +      "value": "ESLZ-HUB-Matt"
done

2022-07-18 15:34 UTC, mosabami approved these changes

2022-07-18 15:34 UTC, merged